#!/usr/bin/env node
// Generates Sources/PodxCore/Generated/CliTables.generated.swift from the built Node CLI
// (out/ of `pnpm run build:cli`), so the native client parses, validates and recovers with
// the same command specs and constants the Node CLI ships with.
// Usage: node native/podx/scripts/gen-tables.mjs [<out dir>]   (default: <repo>/out)
import { createRequire } from 'node:module'
import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const here = path.dirname(new URL(import.meta.url).pathname)
const repo = path.resolve(here, '../../..')
const outDir = path.resolve(process.argv[2] ?? path.join(repo, 'out'))
const require = createRequire(path.join(outDir, 'noop.js'))

const { COMMAND_SPECS } = require('./cli/specs/index.js')
const boundary = require('./shared/cli-argument-boundary.js')
const conflict = require('./shared/automation-owner-conflict.js')
const conflictRecovery = require('./cli/automation-owner-conflict-recovery.js')
const selectorRecovery = require('./cli/worktree-selector-recovery.js')
const evidence = require('./shared/orchestration-compatibility-evidence.js')
const computerRecovery = require('./shared/computer-use-error-recovery.js')

const lit = (s) => JSON.stringify(s)
const arr = (xs) => `[${xs.map(lit).join(', ')}]`

// SECRET_KEYS is module-private; recover it by observing redaction, the only contract that matters.
const secretKeys = []
{
  const probe = {}
  const candidates = [
    'launchToken',
    'connectionIncarnation',
    'attachmentId',
    'compatibilityEvidence',
    'orchestrationCompatibilityEvidence',
    'ORCA_AGENT_LAUNCH_TOKEN',
    evidence.ORCHESTRATION_COMPATIBILITY_HOST_INCARNATION_ENV,
    evidence.ORCHESTRATION_COMPATIBILITY_ATTACHMENT_ENV
  ]
  for (const key of candidates) {
    probe[key] = 'x'
  }
  const redacted = evidence.redactOrchestrationCompatibilitySecrets(probe)
  for (const key of candidates) {
    if (redacted[key] === '[redacted]') {
      secretKeys.push(key)
    }
  }
}

const conflictCodes = Object.values(conflict.AUTOMATION_OWNER_CONFLICT_CODES)
const recoveryRows = conflictCodes.map(
  (code) =>
    `    (${lit(code)}, ${arr(conflictRecovery.automationOwnerConflictRecovery(code).nextSteps)}),`
)

const specRows = COMMAND_SPECS.map((spec) => {
  const roles = spec.identityFlagRoles ? Object.keys(spec.identityFlagRoles) : []
  return [
    '    CommandSpec(',
    `      path: ${arr(spec.path)},`,
    `      aliases: [${(spec.aliases ?? []).map(arr).join(', ')}],`,
    `      passthrough: ${spec.argumentMode === 'passthrough'},`,
    `      hidden: ${spec.hidden === true},`,
    `      allowedFlags: ${arr(spec.allowedFlags)},`,
    `      repeatableFlags: ${arr(spec.repeatableFlags ?? [])},`,
    `      positionalArgs: ${arr(spec.positionalArgs ?? [])},`,
    `      identityFlags: ${arr(roles)}`,
    '    ),'
  ].join('\n')
})

const revision = (() => {
  try {
    return execFileSync('git', ['-C', repo, 'rev-parse', '--short=10', 'HEAD'], {
      encoding: 'utf8'
    }).trim()
  } catch {
    return 'unknown'
  }
})()

const source = `// Generated by native/podx/scripts/gen-tables.mjs from the built Node CLI at ${revision}.
// Do not edit by hand; rerun the generator after the CLI's specs or recovery tables change.

public let CLI_GLOBAL_FLAGS: [String] = ${arr(boundary.CLI_GLOBAL_FLAGS)}
public let CLI_GLOBAL_VALUE_FLAGS: [String] = ${arr(boundary.CLI_GLOBAL_VALUE_FLAGS)}
public let CLI_BOOLEAN_FLAGS: Set<String> = ${arr([...boundary.CLI_BOOLEAN_FLAGS])}

public let SECRET_KEYS: Set<String> = ${arr(secretKeys)}

public let AUTOMATION_OWNER_CONFLICT_RECOVERY: [(code: String, nextSteps: [String])] = [
${recoveryRows.join('\n')}
]

public let WORKTREE_SELECTOR_FORMS: [String] = ${arr([...selectorRecovery.WORKTREE_SELECTOR_FORMS])}

public let COMPUTER_INVALID_ARGUMENT_NEXT_STEPS: [String] = ${arr(computerRecovery.computerUseErrorRecoveryData('invalid_argument')?.nextSteps ?? [])}

public let COMMAND_SPECS: [CommandSpec] = [
${specRows.join('\n')}
]
`

const target = path.join(here, '..', 'Sources', 'PodxCore', 'Generated')
mkdirSync(target, { recursive: true })
writeFileSync(path.join(target, 'CliTables.generated.swift'), source)
console.log(`wrote ${COMMAND_SPECS.length} specs, ${secretKeys.length} secret keys (${revision})`)
