"""Synthetic parity cases. Fields: name, command, optional cwd (relative to fixture),
kill_after_ms, settle_ms, leftover_marker, normalize (regexes), env, expect_diff."""

PIDS = [r"\b\d{2,7}\b"]

CASES = [
    # basics
    {"name": "echo", "command": "echo hi"},
    {"name": "printf_nonl", "command": "printf x"},
    {"name": "empty_output", "command": "true"},
    {"name": "pipe", "command": "printf 'b\\na\\nc\\n' | sort | head -2"},
    {"name": "pipe_status", "command": "false | true; echo $? ${pipestatus[@]}"},
    {"name": "redirect_out", "command": "echo data > out.txt && cat out.txt"},
    {
        "name": "redirect_append",
        "command": "echo 1 >> a.log; echo 2 >> a.log; cat a.log",
    },
    {"name": "stderr", "command": "echo err >&2; echo out"},
    {
        "name": "interleave",
        "command": "for i in 1 2 3; do echo o$i; echo e$i >&2; done",
    },
    {"name": "and_or_chain", "command": "true && false || echo recovered && echo end"},
    {"name": "subshell", "command": "(cd sub; pwd); pwd"},
    {"name": "cmd_subst", "command": 'x=$(echo sub); echo "[$x]"'},
    {"name": "funcdef", "command": "f() { echo in-f $1; }; f arg"},
    {"name": "source_file", "command": "source ./script.sh; echo after=$SCRIPT_VAR"},
    {"name": "env_no_persist", "command": "export PNB_X=1; echo $PNB_X"},
    {"name": "long_arg", "command": "echo " + "x" * 100000 + " | wc -c"},
    # heredocs and quoting
    {"name": "heredoc_quoted", "command": "cat <<'EOF'\n$HOME literal\nEOF"},
    {"name": "heredoc_expand", "command": "cat <<EOF\nhome=$HOME\nEOF"},
    {"name": "heredoc_dash", "command": "cat <<-EOF\n\tindented\n\tEOF"},
    {"name": "heredoc_then_cmd", "command": "cat <<EOF > h.txt\nline\nEOF\ncat h.txt"},
    {"name": "multiline_quote", "command": "echo 'x\ny'"},
    {"name": "single_quotes", "command": "echo \"a'b\" 'c\"d' $'e\\tf'"},
    {"name": "nul_redirect", "command": "echo gone > NUL; ls"},
    # cwd tracking
    {"name": "cd_persist", "command": "cd sub && pwd"},
    {"name": "cd_symlink", "command": "cd link && pwd && pwd -P"},
    {"name": "cd_fail", "command": "cd nonexistent"},
    {"name": "cd_then_fail", "command": "cd sub && false"},
    {"name": "cd_in_subdir_start", "command": "pwd", "cwd": "sub"},
    {"name": "exec_replace", "command": "exec echo replaced"},
    {"name": "exit_middle", "command": "echo a; exit 0; echo b"},
    {"name": "return_top", "command": "return 5"},
    # exit codes, errors
    {"name": "exit_3", "command": "exit 3"},
    {"name": "false", "command": "false"},
    {"name": "subshell_exit", "command": "(exit 42); echo $?"},
    {"name": "set_e", "command": "set -e; false; echo not-reached"},
    {"name": "set_u", "command": "set -u; echo $UNDEFINED_PNB_VAR"},
    {"name": "syntax_error", "command": "echo ("},
    {"name": "syntax_error_late", "command": "echo ok\nif then fi"},
    {"name": "cmd_not_found", "command": "pnb_no_such_cmd_xyz"},
    {"name": "glob_nomatch", "command": "ls *.nomatch"},
    {"name": "ext_glob_off", "command": "echo ^x 'a#b' && ls *.txt"},
    {"name": "self_term", "command": "kill -TERM $$"},
    {"name": "self_kill", "command": "kill -KILL $$"},
    {"name": "self_int", "command": "kill -INT $$; echo after"},
    {"name": "segv_child", "command": "sh -c 'kill -SEGV $$'; echo rc=$?"},
    # stdin
    {"name": "stdin_devnull", "command": "cat; echo rc=$?"},
    {
        "name": "stdin_open_heredoc",
        "command": 'cat <<EOF\nz\nEOF\nread -t 1 y; echo "read_rc=$?"',
    },
    {"name": "input_redirect", "command": "sort < file.txt"},
    {
        "name": "stdin_type_heredoc",
        "command": "cat <<EOF\nz\nEOF\n[ -S /dev/stdin ] && echo sock; [ -p /dev/stdin ] && echo pipe; [ -c /dev/stdin ] && echo chr",
    },
    # output shapes
    {"name": "large_stdout", "command": "seq 1 300000"},
    {"name": "large_stderr", "command": "seq 1 100000 >&2"},
    {
        "name": "large_mixed",
        "command": "for i in $(seq 1 2000); do echo out$i; echo err$i >&2; done",
    },
    {"name": "utf8", "command": "printf 'zażółć gęślą jaźń\\n'; ls"},
    {"name": "nul_bytes", "command": "printf 'a\\0b\\0c'"},
    {"name": "binary", "command": "printf '\\x00\\xff\\xfe\\x80'"},
    {"name": "no_trailing_nl", "command": "printf 'a\\nb'"},
    # snapshot functions, aliases, options
    {
        "name": "type_shims",
        "command": "type find | head -1; type grep | head -1; type rg | head -1; type pkill | head -1",
    },
    {"name": "grep_shim", "command": "grep -c hello file.txt; grep -rn hello . | sort"},
    {"name": "find_shim", "command": "find . -name '*.txt' | sort"},
    {"name": "rg", "command": "rg -n hello . | sort"},
    {"name": "alias_snapshot", "command": "alias | head -2"},
    {"name": "options", "command": "setopt | sort | tr '\\n' ' '"},
    {
        "name": "param_names",
        "command": "print -l ${(k)parameters} | sort | grep -v -e '^_$' | shasum",
    },
    {
        "name": "param_names_list",
        "command": "print -l ${(k)parameters} | sort | tr '\\n' ' '",
        "normalize": [],
    },
    {"name": "func_names", "command": "print -l ${(k)functions} | sort | shasum"},
    {"name": "aliases_all", "command": "alias | shasum"},
    {"name": "env_names", "command": "env | cut -d= -f1 | sort | tr '\\n' ' '"},
    {"name": "env_values", "command": "env | sort | shasum"},
    {"name": "fd_list", "command": "ls /dev/fd | tr '\\n' ' '"},
    {
        "name": "fd_list_heredoc",
        "command": "cat <<EOF\nz\nEOF\nls /dev/fd | tr '\\n' ' '",
    },
    {"name": "traps", "command": "trap; echo end"},
    {"name": "limits", "command": "umask; ulimit -n; ulimit -s; ulimit -u"},
    {
        "name": "tty",
        "command": "tty; [ -t 0 ] && echo t0; [ -t 1 ] && echo t1; echo end",
    },
    {
        "name": "stdout_regular",
        "command": "[ -f /dev/stdout ] && echo regular; stat -f %HT /dev/stdout",
    },
    {
        "name": "leader",
        "command": '[ "$(ps -o pgid= -p $$ | tr -d \' \')" = "$$" ] && echo pgid-leader; [ "$(ps -o sess= -p $$ | tr -d \' \')" != "" ] && echo has-sess',
    },
    {"name": "dollar_underscore", "command": 'echo "[$_]"'},
    {"name": "dollar_zero", "command": "echo $0 $ZSH_NAME $SHLVL"},
    {
        "name": "exec_string",
        "command": "echo ${#ZSH_EXECUTION_STRING}",
        "expect_diff": True,
    },
    {"name": "pid_ppid", "command": "echo $$ $PPID", "normalize": PIDS},
    {"name": "lineno", "command": "echo $LINENO\necho $LINENO"},
    {
        "name": "funcstack",
        "command": 'echo "[${funcstack[*]}][${funcfiletrace[*]}][${funcsourcetrace[*]}]"',
    },
    {"name": "prompt_N", "command": "print -P '%N %i'"},
    {
        "name": "jobs",
        "command": "sleep 0.1 & jobs | sed 's/[0-9][0-9]*/N/g'; wait; echo done",
    },
    {
        "name": "python_tty",
        "command": "python3 -I -c 'import sys; print(sys.stdout.isatty(), sys.stdin.isatty(), sys.stdout.encoding)'",
    },
    {
        "name": "git_log",
        "command": "git -C repo log --format=%s | head -3; git -C repo status --short | wc -l",
    },
    {
        "name": "git_status_cd",
        "command": "cd repo && git status --porcelain=v1 && git rev-parse --show-toplevel",
    },
    # background, timing, kill
    {
        "name": "bg_late_write",
        "command": "(sleep 0.3; echo late) & echo early",
        "settle_ms": 700,
    },
    {
        "name": "bg_leftover",
        "command": "sleep 7.7123 & echo started",
        "leftover_marker": "7.7123",
    },
    {
        "name": "bg_disown",
        "command": "sleep 6.6123 & disown; echo d",
        "leftover_marker": "6.6123",
    },
    {"name": "sleep_short", "command": "sleep 0.2; echo ok"},
    {
        "name": "kill_trap_term",
        "command": "trap 'echo got-term; exit 9' TERM; sleep 30.4567 & wait",
        "kill_after_ms": 500,
        "leftover_marker": "30.4567",
    },
    {
        "name": "kill_ignore_term",
        "command": "trap '' TERM; sleep 5.4321",
        "kill_after_ms": 300,
        "leftover_marker": "5.4321",
    },
    {
        "name": "kill_tree",
        "command": "sleep 31.98761 & sleep 32.98761 & wait",
        "kill_after_ms": 300,
        "leftover_marker": ".98761",
    },
    {
        "name": "kill_fg_sleep",
        "command": "echo before; sleep 33.333; echo after",
        "kill_after_ms": 300,
        "leftover_marker": "33.333",
    },
    {
        "name": "kill_setsid_child",
        "command": "python3 -I -c 'import os,time; os.setsid(); time.sleep(34.98762)' & sleep 35.98762",
        "kill_after_ms": 400,
        "leftover_marker": ".98762",
    },
    # residue probes added after the first warm runs
    {"name": "zmodload_list", "command": "zmodload | tr '\\n' ' '"},
    {"name": "eval_context", "command": "echo $ZSH_EVAL_CONTEXT"},
    {"name": "seconds", "command": "echo $SECONDS"},
    {"name": "fd3_closed", "command": "print -u 3 x; echo rc=$?"},
    {"name": "fd9_closed", "command": "echo hi >&9; echo rc=$?"},
    {"name": "exit_trap", "command": "trap 'echo on-exit' EXIT; echo body"},
    {"name": "err_trap", "command": "trap 'echo on-err' ERR; false; echo after"},
    {"name": "dup_stdout", "command": "exec 3>&1; echo via3 >&3; exec 3>&-; echo done"},
    {"name": "stdin_cat_heredoc", "command": "cat <<EOF\nz\nEOF\ncat /dev/stdin & sleep 0.3; kill %1 2>/dev/null; echo end"},
    {"name": "ppid_name", "command": "ps -o comm= -p $PPID", "expect_diff": True},
    {"name": "nice", "command": "ps -o nice= -p $$"},
    {"name": "times", "command": "times | wc -l"},
    {"name": "hash_table", "command": "hash | wc -l"},
    {"name": "dirstack", "command": "dirs -v; echo $OLDPWD | sed 's|.*/||'"},
    {"name": "histcmd", "command": "echo $HISTCMD ${#history}"},
    {"name": "random_type", "command": "echo ${(t)RANDOM} ${(t)SECONDS}"},
    {"name": "zsh_subshell", "command": "echo $ZSH_SUBSHELL; (echo $ZSH_SUBSHELL)"},
    {"name": "path_hash_rg", "command": "whence -p rg; whence -w rg"},
    {"name": "fd_flags", "command": "python3 -I -c 'import os,fcntl; print([oct(fcntl.fcntl(i, fcntl.F_GETFL)) for i in (1,2)], os.get_blocking(1))'"},
    {"name": "stdin_flags_heredoc", "command": "cat <<EOF\nz\nEOF\npython3 -I -c 'import os,stat,fcntl; st=os.fstat(0); print(stat.S_ISSOCK(st.st_mode), oct(fcntl.fcntl(0, fcntl.F_GETFL)))'"},
    {"name": "same_description", "command": "python3 -I -c 'import os; os.write(1,b\"a\"); print(os.lseek(2,0,1))'"},
    {"name": "qos", "command": "python3 -I -c 'import ctypes; l=ctypes.CDLL(None); print(l.qos_class_self())'"},
    {"name": "sigmask", "command": "python3 -I -c 'import signal; print(sorted(signal.pthread_sigmask(signal.SIG_BLOCK, [])))'"},
    {"name": "sigign", "command": "python3 -I -c 'import signal; print([s for s in range(1,32) if s not in (9,17) and signal.getsignal(s)==signal.SIG_IGN])'"},
    {"name": "rlimits", "command": "ulimit -a | shasum"},
]
