#!/usr/bin/env bash
# Re-runs the generated layers listed under "generated" in pod-stack.json on top of a commit, one
# commit per layer. A codemod over the whole assembled stack then re-applies after every assembly
# and every upstream sync, instead of being rebased (and conflicting) like a hand-written commit.
#
# Usage: scripts/pod-generated.sh [--manifest PATH] <commit>
#   Generated commits already on top of <commit> (Pod-Generated trailer) are dropped first, so a
#   re-run replaces them. Prints the resulting commit on stdout; progress goes to stderr.
#
# Manifest:
#   "generated": [
#     { "name": "pod-decouple", "requires": "product/scripts/pod-decouple.mjs",
#       "run": ["node", "product/scripts/pod-decouple.mjs", "--apply"],
#       "check": ["node", "product/scripts/pod-decouple.mjs", "--check"],
#       "subject": "chore(pod): decouple the runtime from Orca (generated by pod-decouple)",
#       "forkOnly": "generated decouple layer" }
#   ]
#   A layer runs only when the tree has its "requires" file. "run" changes the tree; a non-zero exit
#   fails. "check" runs after it and must exit 0, which proves a second run would change nothing.
#
# Exit codes: 0 done, 1 usage or environment error, 5 a layer failed or is not idempotent.
set -euo pipefail

die() {
  printf 'pod-generated: %s\n' "$*" >&2
  exit 1
}

manifest=''
commit=''
while [ $# -gt 0 ]; do
  case $1 in
    --manifest) manifest=${2:?--manifest needs a path}; shift 2 ;;
    -h|--help) sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) die "unknown option: $1" ;;
    *) [ -z "$commit" ] || die "one commit only"; commit=$1; shift ;;
  esac
done
[ -n "$commit" ] || die "usage: scripts/pod-generated.sh [--manifest PATH] <commit>"
root=$(git rev-parse --show-toplevel)
manifest=${manifest:-$root/pod-stack.json}
[ -f "$manifest" ] || die "no manifest at $manifest"
tip=$(git rev-parse --verify "$commit^{commit}") || die "$commit is not a commit"

while [ -n "$(git log -1 --format='%(trailers:key=Pod-Generated,valueonly)' "$tip")" ]; do
  printf '    - dropping the old generated layer %s %s\n' "$(git rev-parse --short "$tip")" "$(git log -1 --format=%s "$tip")" >&2
  tip=$(git rev-parse "$tip^")
done

# One layer per record: name, requires, subject, forkOnly, then run and check as NUL-separated argv.
layers=$(node -e '
const m = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))
const fail = (msg) => { console.error("pod-generated: " + msg); process.exit(1) }
const list = m.generated === undefined ? [] : m.generated
if (!Array.isArray(list)) fail("\"generated\" must be an array")
const out = []
list.forEach((g, i) => {
  const where = "generated[" + i + "]"
  for (const k of ["name", "requires", "subject", "forkOnly"])
    if (typeof g[k] !== "string" || !g[k] || /[\t\n]/.test(g[k])) fail(where + " needs a one-line \"" + k + "\"")
  for (const k of ["run", "check"])
    if (!Array.isArray(g[k]) || g[k].length === 0 || g[k].some((a) => typeof a !== "string")) fail(where + " needs \"" + k + "\" as an argv array")
  out.push([g.name, g.requires, g.subject, g.forkOnly, Buffer.from(JSON.stringify(g.run)).toString("base64"), Buffer.from(JSON.stringify(g.check)).toString("base64")].join("\t"))
})
console.log(out.join("\n"))
' "$manifest")

if [ -z "$layers" ]; then
  printf '%s\n' "$tip"
  exit 0
fi

wt=''
cleanup() { [ -z "$wt" ] || git worktree remove --force "$wt" >/dev/null 2>&1 || rm -rf "$wt"; }
trap cleanup EXIT

argv_of() { node -e 'for (const a of JSON.parse(Buffer.from(process.argv[1], "base64").toString())) process.stdout.write(a + "\0")' "$1"; }

while IFS=$'\t' read -r -u 3 name requires subject fork_only run_b64 check_b64; do
  [ -n "$name" ] || continue
  if ! git cat-file -e "$tip:$requires" 2>/dev/null; then
    printf '    (generated layer %s skipped: no %s in the tree)\n' "$name" "$requires" >&2
    continue
  fi
  wt=$(mktemp -d "${TMPDIR:-/tmp}/pod-generated.XXXXXX")
  rmdir "$wt"
  # Hooks off: the repository's post-checkout hook would install packages.
  git -c core.hooksPath=/dev/null worktree add --quiet --detach "$wt" "$tip"
  run=()
  while IFS= read -r -d '' a; do run+=("$a"); done < <(argv_of "$run_b64")
  check=()
  while IFS= read -r -d '' a; do check+=("$a"); done < <(argv_of "$check_b64")

  if ! out=$(cd "$wt" && "${run[@]}" 2>&1); then
    printf '\nGENERATED LAYER FAILED: %s (%s)\n%s\n\nNothing was committed.\n' "$name" "${run[*]}" "$out" >&2
    exit 5
  fi
  if ! out=$(cd "$wt" && "${check[@]}" 2>&1); then
    printf '\nGENERATED LAYER NOT IDEMPOTENT: %s (%s)\n%s\n\nNothing was committed.\n' "$name" "${check[*]}" "$out" >&2
    exit 5
  fi
  git -C "$wt" add -A
  tree=$(git -C "$wt" write-tree)
  if [ "$tree" = "$(git rev-parse "$tip^{tree}")" ]; then
    printf '    (generated layer %s changed nothing)\n' "$name" >&2
  else
    files=$(git diff --name-only "$tip" "$tree" | wc -l | tr -d ' ')
    message=$(printf '%s\n\nGenerated by `%s` on the assembled stack, and re-run after every assembly and\nupstream sync instead of being rebased.\n\nFork-only: %s\nPod-Generated: %s\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n' \
      "$subject" "${run[*]}" "$fork_only" "$name")
    tip=$(git commit-tree "$tree" -p "$tip" <<<"$message")
    printf '    + %s (generated by %s, %d file(s))\n' "$(git rev-parse --short "$tip")" "$name" "$files" >&2
  fi
  git worktree remove --force "$wt"
  wt=''
done 3<<<"$layers"

printf '%s\n' "$tip"
